version: '3.9'

services: 
  mongo: 
    image: mongo:latest 
    container_name: my-mongo 
    restart: always 
    environment: 
      MONGO_INITDB_ROOT_USERNAME: rootuser 
      MONGO_INITDB_ROOT_PASSWORD: rootpassword 
    ports: 
      - 27017:27017 
    volumes: 
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
